* Client side work
* DONE [100%] refactoring works
** DONE change the ~nk_wl_impl_*~ calls
   This allows the client to have multiple gui windows at its disposal. Or a
   simple fullscreen application.
** DONE the drawing of complex applications.
   You never tried one, I mean, never actually tried the complex programs.
** DONE remove the 4 callbacks(ptron, ptrpress) make make them into one event
   If you pass as an event struct, then you will need to create additional
   struct just for event.
** DONE add pointer's resize/maximize/minimize grab
*** DONE simple resize handler(by every event)
    This does not work apparently. allocating new buffers within the frame is
    probably too much
*** DONE add defered method resizing method, using pending information.
*** CANC use the defered method to accumlate the mouse drawing
*** TODO


* [0%] BUGS
** TODO twclient leak
   There are currently leaks in the use of `xkbcommon` and `wl_get_keyboard`. I
   called the corresponding destructor but there are still leaks.
** repeated key in the non edit environment
   The **textedit** seems fine but other cases have problems
