name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: git submodule update --init --recursive
    - name: docker env
      uses: docker://archlinux/base:latest
    - name: env
      run: |
        sudo pacman -Syu --needed --noconfirm weston libxkbcommon pixman mesa wayland libglvnd wayland-protocols fontconfig freetype2
        sudo pacman -Syu --needed --noconform cmake make gcc clang musl git meson ninja rsync
    - name: build
      run: mkdir -p build && cd build && cmake .. && make 
