name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: git submodule update --init --recursive
    - name: run with docker env
      uses: docker://archlinux/base:latest
      with:
        entrypoint: ./.github/actions/entrypoint.sh
